dev-start:
	python manage.py runserver --settings=todolist.settings
dev-migrate:
	python manage.py migrate --settings=todolist.settings
dev-makemigrations:
	python manage.py makemigrations --settings=todolist.settings
dev-test:
	python manage.py test --settings=todolist.settings
dev-superuser:
	python manage.py createsuperuser --settings=todolist.settings

# Install requirements
install-dev:
	pip install -r requirements/dev.txt