# Generated by Django 4.2.11 on 2024-05-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
